### ISSUE TITLE
Undo leaves text highlighted in visual mode.

### ISSUE THREAD

**Issue by jordwalke** [WarWithinMe/xVim#2]
If you highlight text in visual mode and delete it, when you undo the text remains highlighted. In vim, undoing deletes won't leave the deleted text highlighted.

**Comment by jordwalke** [comment]
Correction, you don't even need to highlight text and then delete it - any kind of deletion has this problem

**Comment by WarWithinMe** [comment]
Using `u` to undo now won't select text any more...

Note that use `ctrl+z` to undo will still select text, because the application interpret `ctrl+z` before xvim has its chance.
One way to overcome this is :
-  bind the application's undo command to `ctrl+shift+z` 
-  Then map `ctrl+z` to `u` in xvim using the keymap stuff....

**Comment by jordwalke** [comment]
This sounds very reasonable

**Comment by WarWithinMe** [comment]
My bad, made a wrong statement....
The way to make `ctrl+z` not select text is : map `ctrl+z` to `u`, not `ctrl+shift+z`
