### ISSUE TITLE
Snippets placements don't work in visual mode

### ISSUE THREAD

**Issue by jordwalke** [WarWithinMe/xVim#4]
In Chocolat editor, when you are expanding snippets, when on placeholders the editor acts like vim in visual mode. This makes snippets unusable.

**Comment by WarWithinMe** [comment]
Fixed.
Now in chocolat, using tab to select `/* token */` will not enter visual mode any more.

**Comment by jordwalke** [comment]
This issue does not seem to be fixed.
If you use the for loop snippet, for->tab when the text is highlighted pressing "s" for example, does not replace the text with s, but rather it deletes the first character.

**Comment by WarWithinMe** [comment]
I was testing `if` snippet when fixing this problem. I thought that all the tab-able stuff are like `/* code */`... Turns out I was wrong.

In Xcode, tab-able token are always reported by the editor as '0xFFFC', so that the token can be identified.
But in chocolat, there's no way to identified them, because token are reported as plain text . One way I can think of for now is never enter visual mode after a `tab`, which will make code very tricky...

**Comment by jordwalke** [comment]
Seems like it's going to be tough to do this kind of stuff without having application specific hacks on top of xVim.

**Comment by atg** [comment]
In Chocolat b6 with xVim integrated, I temporarily disable xVim when a snippet is being edited, so it's not really a problem now.

**Comment by WarWithinMe** [comment]
Thanks fileability. The issue finally can be closed.
